### ISSUE TITLE
Add-on car bug

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_customs#10]
https://youtu.be/N39sCPpCEBM

**Comment by NEvermeant77** [comment]
this is not bug. you have to manual name your add-on vehicle. otherwise will show null as a vehicle name in game

**Comment by renzuzu** [comment]
im not sure how to reproduce this, as my custom addon shows a Vehicle parts lists (if that is what your rooting off)

**Comment by mistr140** [comment]
normally we add an add-on car from tuning but it didn't work

**Comment by Dokman** [comment]
i'll try to reproduce it.

**Comment by Dokman** [comment]
> this is not bug. you have to manual name your add-on vehicle. otherwise will show null as a vehicle name in game

with the hash no?

**Comment by renzuzu** [comment]
Re open when theres a repro
