### ISSUE TITLE
ORIGINAL ERROR SCRIPT

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_customs#100]
Fix?¿
![Captura](https://user-images.githubusercontent.com/65845786/170567911-0410572e-4aa4-41b3-a03c-6be7e37a7c2e.PNG)

**Comment by Dokman** [comment]
what version of esx or qbcore are u using?

**Comment by Gameadictive** [comment]
Legacy

**Comment by Dokman** [comment]
I cannot reproduce that error
