### ISSUE TITLE
Upgrade menu don`t open

### ISSUE THREAD

**Issue by HaosKid** [renzuzu/renzu_customs#103]
Do anyone know why I get those errors? This happens when I want to open upgrade menu.
![image](https://user-images.githubusercontent.com/77285167/175922223-92d34f8f-380b-4328-a64d-9db0953675c7.png)

I also tried Config.usePopui = false but then I get those errors
![image](https://user-images.githubusercontent.com/77285167/175922174-fd63686c-5399-4460-b579-80ec4e02d883.png)

I use QBCore

**Comment by jarrad88** [comment]
i am also getting the same error using qbcore

**Comment by TrustedPunch** [comment]
Hey!

Its a simple scripting issue by @renzuzu don't worry!

1. Go in the file "client/events.lua" @ line 541 you delete the **_**

2. Save this file

3. Restart your server and it's done!
