### ISSUE TITLE
Turbo sound

### ISSUE THREAD

**Issue by bazres** [renzuzu/renzu_customs#104]
hello 

i installed this source and i had a problem 

when i installed custom turbo street or racing , car after 10 min maked a sound like engine crashed i changed turbo and changed engine but not solved the problem 

sound like sssssssssssssssssssss and not was mouted 

please check

**Comment by TrustedPunch** [comment]
Hey @bazres , I have a fix for you.

File: client/client.lua
Line: 160

**Original:**
if not sound then
	soundofnitro = PlaySoundFromEntity(GetSoundId(), "Flare", vehicle , "DLC_HEISTS_BIOLAB_FINALE_SOUNDS", 0, 0)
	sound = true
end

**Fix (without sound):**
--[[
if not sound then
	soundofnitro = PlaySoundFromEntity(GetSoundId(), "Flare", vehicle , "DLC_HEISTS_BIOLAB_FINALE_SOUNDS", 0, 0)
	sound = true
end
]]--
