### ISSUE TITLE
Addon Cars in the Menu = Null

### ISSUE THREAD

**Issue by ItFixx** [renzuzu/renzu_customs#106]
Addon cars are shown as 'Null' in the menu which is annoying, can anyone help me?

**Comment by TrustedPunch** [comment]
Hey!

1. Make a file like "vehicle_names.lua".

2. Insert this code:

```
Citizen.CreateThread(function()
AddTextEntry('ingamename','nametodisplay')
end)
```


**Example:**
```
Citizen.CreateThread(function()
AddTextEntry('c63','Mercedes-Benz AMG C63')
end)
```

3. Add the file to your resource.
