### ISSUE TITLE
Price goes up, when changing primary color every "tick"

### ISSUE THREAD

**Issue by SumnDaiy** [renzuzu/renzu_customs#11]
https://streamable.com/oryyv6

**Comment by renzuzu** [comment]
yea its supposed to be like that, you can edit the price right now in JS:line335
```
function SetCustomColor(event) {
    totalcost = totalcost + 100
    addbill('Custom Paint',totalcost,totalcost,'paint')
    document.getElementById("cost").innerHTML = totalcost.toFixed(1);
    upgraded['paint'] = 'Custom Paint'
    $.post("https://renzu_customs/SetCustomColor", JSON.stringify({ r: hexToRgb(event.target.value).r, g:hexToRgb(event.target.value).g, b:hexToRgb(event.target.value).b, type:colortype}));
}

```

i will make this as optional and price can be configure in later updates

**Comment by SumnDaiy** [comment]
I think instead of adding 100$ every "tick" you should have a "confirm" button and then add fix amount. Makes more sense to me.

**Comment by FragOutGR** [comment]
I'd like to second this as an issue. I think this could be a particularly large issue if you were trying to show a customer different colors and you were getting charged again every time you switched colors.

**Comment by renzuzu** [comment]
fix prices for now
