### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by PetaZero** [renzuzu/renzu_customs#110]
Hello, I am having an error, it tells me that a table is missing which does not come in the sql file.

I am ESX Legacy

![Captura de pantalla (1084)](https://user-images.githubusercontent.com/94184298/192335460-d41894ea-bbc1-4a38-b1bc-bc74741cdcbf.png)

**Comment by JustGamerNL** [comment]
Does the script work in game? If so it doesnt matter (as far as i know, because i get a lot of errors all the time but my scripts all work)
