### ISSUE TITLE
list of extras

### ISSUE THREAD

**Issue by lush0n3** [renzuzu/renzu_customs#118]
Hello dear, good evening.

I am setting up this script which I love and ran into this problem:

Vehicle extras are not listed correctly in the interface and are applied all together

Even so, the total of extras that the vehicle has appear in the interface, but they do not change their status.

I leave you a video of evidence

https://streamable.com/uoqtx3

best regards

**Comment by renzuzu** [comment]
can you give a vehicle model? so i can test properly

**Comment by lush0n3** [comment]
> can you give a vehicle model? so i can test properly

the openwheel2 vehicle has quite a few extra parts

**Comment by renzuzu** [comment]
tf, yea this was broken.
https://github.com/renzuzu/renzu_customs/commit/726e129619c504812cfbeb7559e21123c4310f1c fixed
