### ISSUE TITLE
possible to use with society_mechanic

### ISSUE THREAD

**Issue by R3dzkin** [renzuzu/renzu_customs#119]
hi , i want to use your script with my society mechanic :

TriggerEvent('esx_addonaccount:getSharedAccount', 'society_mechanic', function(account)
            account.money = value
        end)
        -- your owned job money here
    end
    while value == -1 and count < 150 do count = count + 1 Wait(0) end
    return value
end

RegisterServerCallBack_('renzu_customs:pay', function (source, cb, t, shop, vclass)
    local src = source  
    local xPlayer = GetPlayerFromId(src)
    local identifier = xPlayer.identifier
    local prop = t.prop
    local cost = tonumber(t.cost)
    local jobmoney = 0
    if cost == 1 then
        cost = 0
        t.cost = 0
    end
    local vclass = tonumber(vclass)
    if not Config.FreeUpgradeToClass[vclass] and not Config.JobPermissionAll and xPlayer.getMoney() >= t.cost or not Config.FreeUpgradeToClass[vclass] and Config.JobPermissionAll and Config.Customs[shop].job == xPlayer.job.name and Jobmoney(xPlayer.job.name,xPlayer) >= t.cost then
        local result = CustomsSQL(Config.Mysql,'fetchAll','SELECT * FROM '..vehicletable..' WHERE UPPER(plate) = @plate', {
            ['@plate'] = prop.plate:upper()
        })
        if result[1] then
            CustomsSQL(Config.Mysql,'execute','UPDATE '..vehicletable..' SET `'..vehiclemod..'` = @'..vehiclemod..' WHERE UPPER(plate) = @plate', {
                ['@'..vehiclemod..''] = json.encode(prop),
                ['@plate'] = prop.plate:upper()
            })
            if not Config.JobPermissionAll then --if other player
                xPlayer.removeMoney(cost)
            elseif Config.JobPermissionAll and not Config.UseRenzu_jobs then -- job owned without renzu_jobs
                TriggerEvent('esx_addonaccount:getSharedAccount', 'society_mechanic', function(account)
                    account.removeMoney(cost)
                end)
            end
            TriggerClientEvent('renzu_notify:Notify', src, 'success','Customs', 'Payment Success - Upgrade has been Installed')
            if Config.UseRenzu_jobs and not Config.JobPermissionAll then
                addmoney = exports.renzu_jobs:addMoney(tonumber(t.cost),Config.Customs[shop].job,source,'money',true)
            elseif Config.UseRenzu_jobs and Config.JobPermissionAll and Config.Customs[shop].job == xPlayer.job.name then
                removemoney = exports.renzu_jobs:removeMoney(tonumber(t.cost),Config.Customs[shop].job,source,'money',true)
            end
            cb(true)
        elseif not Config.OwnedVehiclesOnly then
            if not Config.JobPermissionAll and xPlayer.getMoney() >= tonumber(t.cost) or Config.JobPermissionAll and Config.Customs[shop].job == xPlayer.job.name and Jobmoney(xPlayer.job.name,xPlayer) >= tonumber(t.cost) then
                if not Config.JobPermissionAll then --if other player
                    xPlayer.removeMoney(cost)
                elseif Config.JobPermissionAll and not Config.UseRenzu_jobs then -- job owned without renzu_jobs
                    TriggerEvent('esx_addonaccount:getSharedAccount', 'society_mechanic', function(account)
                        account.removeMoney(cost)
                    end)
                end
                
                
                
                
                
                i wrote this but doesnt work
                
                1.20 version on esx 1.2

**Comment by Gameadictive** [comment]
I want the same
