### ISSUE TITLE
Custom color not saving in garage

### ISSUE THREAD

**Issue by revcityrp** [renzuzu/renzu_customs#122]
Other upgrades gets saved, but paint color doesn't save. It goes back to the original color before the upgrade when getting pulled out of the garage.

**Comment by renzuzu** [comment]
use the exports for property setter.

you need to change your setvehicleproperties from other scripts. eg. garage.

this is only for the rgb paints.

**Comment by revcityrp** [comment]
Hi. I'm using jg-advancedgarages for ESX. Unfortunately its files is locked, though there is an editable file for client.lua.

I put the export here (correct me if I'm wrong pls) 
![image](https://user-images.githubusercontent.com/85905535/203303385-c4773788-15cc-4cf4-9526-60f71297befc.png)

But it shows this error:
![image](https://user-images.githubusercontent.com/85905535/203303419-d594bd3a-206c-4608-9188-691774709a1e.png)


Should I just change my garage script?

**Comment by renzuzu** [comment]
i dont know if that is the right event to pass that exports.
you could try

vehicleDbData.vehicle

if thats have a data that could be the one you could pass to set the setter of exports

im sporry i could not much help since that is encrypted
