### ISSUE TITLE
Use menu

### ISSUE THREAD

**Issue by Marquesss12** [renzuzu/renzu_customs#123]
Hi, The menu opens but I can't change it, when I press "pay now" it just stays the same and doesn't change anything.
This is what we have
![image](https://user-images.githubusercontent.com/117491253/204113997-c832cb20-efad-4df7-9365-71178c874c2a.png)
![image](https://user-images.githubusercontent.com/117491253/204114000-0ecc2a30-9d32-4f06-83f1-e1f95849db0c.png)
![image](https://user-images.githubusercontent.com/117491253/204114002-8cd61304-3b1e-493a-b08d-f303856b6bf9.png)

**Comment by Marquesss12** [comment]
> need more info. your image does not say anything.

To be honest I'm new to this. I wanted to use this script in QBCore and I just edited it in the config. Do I need to change anything else in the code for it to work correctly?

**Comment by Marquesss12** [comment]
What is that renzu_shield/init.lua i  the last photo?

**Comment by renzuzu** [comment]
ignore it , it doesnt stop the resource from working. or remove it on fxmanifest.

>To be honest I'm new to this. I wanted to use this script in QBCore and I just edited it in the config. Do I need to change anything else in the code for it to work correctly?

i made this a drag and drop to qbcore .
is your qbcore is from the official repo?

if possible for you to record a video and upload to streamable or something

**Comment by Marquesss12** [comment]
> 

I'm going to do it, by the way there are two sql, which one?

**Comment by Marquesss12** [comment]
Hi, I changed the notifys and now this happens
https://medal.tv/games/gta-v/clips/KCldpysZMOC4n/d1337zBUatdt?invite=cr-MSxwaDMsNDcxMTcxNCw



I found this in the middle, I suppose it's to adapt to qbcore, but honestly I don't know how to do it :/
![image](https://user-images.githubusercontent.com/117491253/205413556-d295b99a-0270-49ca-9ac7-6abeec323081.png)

**Comment by renzuzu** [comment]
yea thats my newly support for esx society.

but with qb management i dont know, i will look on it.

**Comment by Marquesss12** [comment]
I don't know if it helps, but the exports you mentioned in the comment are these?

https://github.com/qbcore-framework/qb-management/blob/main/fxmanifest.lua

**Comment by renzuzu** [comment]
test it , i m sleeping when i do this commit.

**Comment by Marquesss12** [comment]
> test it , i m sleeping when i do this commit.

Hi! I've been having some issues with the script, the payment is taken from the player and not the society.
I leave the videos to be easier:
https://medal.tv/pt/games/gta-v/clips/KV0m0Gy28tLX0/hHf6Xr1XmTzp

When I put the mod without using the menu it doesn't save:
https://medal.tv/pt/games/gta-v/clips/L17alRY3mrQ_s/d1337Mvp4I3g?invite=cr-MSx5cWYsNDcxMTcxNCw

I need to open the menu and use "pay now" to save:
https://medal.tv/pt/games/gta-v/clips/L18SEqIJlXUmL/kbN2QisKbxZM?invite=cr-MSxjYnksNDcxMTcxNCw


And I can't remove the livery after it's placed:
https://medal.tv/pt/games/gta-v/clips/L1d7OFVFfXszf/pEGMZNrXPltl?invite=cr-MSx5dUEsNDcxMTcxNCw

And the Paint menu does not save the color in any way
