### ISSUE TITLE
Script error account

### ISSUE THREAD

**Issue by UsernameisMike** [renzuzu/renzu_customs#129]
[script:renzu_customs] SCRIPT ERROR: @renzu_customs/server/server.lua:102: attempt to index a nil value (local 'account')
[script:renzu_customs] > ref (@renzu_customs/server/server.lua:102)
[script:renzu_customs] > handler (@esx_addonaccount/server/main.lua:52)
[script:renzu_customs] > Jobmoney (@renzu_customs/server/server.lua:101)
[script:renzu_customs] > ref (@renzu_customs/server/server.lua:143)
[script:renzu_customs] > TriggerServerCallback (@es_extended/server/functions.lua:172)
[script:renzu_customs] > handler (@es_extended/server/common.lua:110)
[script:esx_addonacco] SCRIPT ERROR: error object is not a string
[script:esx_addonacco] > Jobmoney (@renzu_customs/server/server.lua:101)
[script:esx_addonacco] > ref (@renzu_customs/server/server.lua:143)
[script:esx_addonacco] > TriggerServerCallback (@es_extended/server/functions.lua:172)
[script:esx_addonacco] > handler (@es_extended/server/common.lua:110)

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_customs/releases/tag/1.28
