### ISSUE TITLE
Purchasing bug possibly??

### ISSUE THREAD

**Issue by Bluequeen28** [renzuzu/renzu_customs#130]
Notification  says not enough money cabron after trying to install a mod through the menu

**Comment by renzuzu** [comment]
ESX?

**Comment by Bluequeen28** [comment]
Yes

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_customs/releases/tag/1.28 try this latest version

**Comment by Bluequeen28** [comment]
Thankyou will try this and let you know

**Comment by Bluequeen28** [comment]
Do we have to do both files of the sql?
