### ISSUE TITLE
PAYMENT METHOD PROBLEM

### ISSUE THREAD

**Issue by hasidu** [renzuzu/renzu_customs#131]
Hi renzu on my server i have an older version of renzu customs.

so my problem is when mechanic pay for modification of player cars it pay via mechanic money not with mechanic society.

so is there way to auto detect mechanic society and pay for modifications via mechanic soiety ?

**Comment by hasidu** [comment]
??

**Comment by renzuzu** [comment]
> i have an older version of renzu customs

only the latest main branch support society

did you tried it?

**Comment by hasidu** [comment]
not yet i will test it and let you know
