### ISSUE TITLE
Disable Custom Paint

### ISSUE THREAD

**Issue by DeNtrlPredator** [renzuzu/renzu_customs#149]
Is there a way to disable Custom Paint in the paint menu? Our server likes to use this script but wants to make custom paints an exclusive modification that only player mechanics can do.

**Comment by MrUnterhaltung** [comment]
config ---> Delete from 1232--1271

**Comment by DeNtrlPredator** [comment]
> config ---> Delete from 1232--1271

Sadly this did not work. It removed the entire paint menu. I only want to remove custom paints
![image](https://user-images.githubusercontent.com/64099154/218300198-1a7c7a25-c530-4834-81ef-2ffe9a3326b5.png)

**Comment by renzuzu** [comment]
apparently this is hardcoded in UI.
you could disable this by removing that in JS / html
