### ISSUE TITLE
The cursor does not disappear after closing a menu. Impossible to continue.

### ISSUE THREAD

**Issue by andrescaste98** [renzuzu/renzu_customs#150]
When closing any inventory or paint menu, the cursor stays on the screen (if I use ESC or RETURN I can still hear the menu sounds). This makes it impossible to continue doing anything. You need to use /restart or /stop in the renzu_contextmenu-1.8 script. I don't know if this is a problem with renzu-customs or renzu-renzu_contextmenu-1.8.

**Comment by renzuzu** [comment]
rename the resource. eg renzu_contextmenu-1.8 to renzu_contextmenu

do not include auto generated folder name extension from github.

**Comment by andrescaste98** [comment]
Thank you for your prompt response. Now I have the problem that no changes are saved. Neither color, license plate, cosmetics. Nothing. I use QBCore, could you help me?

**Comment by andrescaste98** [comment]
Correction. They are not saved because it indicates to me that I have no money with me. I have set up the script notifications with my notification system and that tells me, I have no money. Obviously I do.

**Comment by renzuzu** [comment]
if this is a job based.
go to qb-management. and put a money for ex. mechanic job
