### ISSUE TITLE
Upgrades not sticking

### ISSUE THREAD

**Issue by Fakiee** [renzuzu/renzu_customs#152]
So my server restarted this morning and now my upgrades are not sticking, after clicking pay it just resets this is in the logs

`[    473516] [b2699_GTAProce]                 7792/ ResourceCache::AddEntry: Saved cache:v1:a44a5fb3ae26637c28c6e6f2421b9978c3adddcc to the index cache.
[    591891] [b2699_GTAProce]                 7792/ ResourceCache::AddEntry: Saved cache:v1:fe0a69a39ffaf0c5bf6dec205cdfabdc10bc2952 to the index cache.
[    603406] [b2699_GTAProce]                 7792/ ResourceCache::AddEntry: Saved cache:v1:fb0fa5679c15a3fa281b36abbf974ea9308b4c53 to the index cache.
[    637047] [b2699_GTAProce]                22048/ ResourceCache::AddEntry: Saved cache:v1:d7e27fe17bd228e1e5ade051d051326204591e80 to the index cache.
[    639281] [b2699_GTAProce]                 7792/ ResourceCache::AddEntry: Saved cache:v1:12f825a79b5e66cc00461cbbf299192f58b9e316 to the index cache.
[    641609] [b2699_GTAProce]                22048/ ResourceCache::AddEntry: Saved cache:v1:8fe410c6c525b0dcf9768f4195f41010bf56beb4 to the index cache.
[    643641] [b2699_GTAProce]                 7792/ ResourceCache::AddEntry: Saved cache:v1:f600661b3f60b0da39dd02d94e063e74117de30a to the index cache.
[    849234] [b2699_GTAProce]             MainThrd/ removing FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[    849234] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[    849234] [b2699_GTAProce]             MainThrd/ removing CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[    849234] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    849234] [b2699_GTAProce]             MainThrd/ removing CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[    849234] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    850078] [b2699_GTAProce]             MainThrd/ Stopping resource renzu_customs
[    850078] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[    850078] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[    850078] [b2699_GTAProce]             MainThrd/ Started resource renzu_customs
[    850078] [b2699_GTAProce]             MainThrd/ 
[    850094] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[    850219] [b2699_GTAProce]  UV loop: httpClient/ Required resources: renzu_customs 
[    850234] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[    850234] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[    850234] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    850234] [b2699_GTAProce]             MainThrd/ loading CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[    850234] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    850234] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    850234] [b2699_GTAProce]             MainThrd/ loading CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[    850234] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    850234] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    850234] [b2699_GTAProce]             MainThrd/ loading FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[    850234] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[    850234] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Mounted renzu_customs (1 of 1)
[    886719] [b2699_GTAProce]             MainThrd/ removing FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[    886719] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[    886719] [b2699_GTAProce]             MainThrd/ removing CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[    886719] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    886719] [b2699_GTAProce]             MainThrd/ removing CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[    886719] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    886766] [b2699_GTAProce]             MainThrd/ Stopping resource renzu_customs
[    886766] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[    886766] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[    886766] [b2699_GTAProce]             MainThrd/ Started resource renzu_customs
[    886766] [b2699_GTAProce]             MainThrd/ 
[    886797] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[    886906] [b2699_GTAProce]  UV loop: httpClient/ Required resources: renzu_customs 
[    886922] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[    886938] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[    886938] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    886938] [b2699_GTAProce]             MainThrd/ loading CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[    886938] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    886938] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    886938] [b2699_GTAProce]             MainThrd/ loading CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[    886938] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[    886938] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    886938] [b2699_GTAProce]             MainThrd/ loading FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[    886938] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[    886938] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Mounted renzu_customs (1 of 1)
[   1084969] [b2699_GTAProce]             MainThrd/ removing FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[   1084969] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[   1084969] [b2699_GTAProce]             MainThrd/ removing CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[   1084969] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[   1084984] [b2699_GTAProce]             MainThrd/ removing CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[   1084984] [b2699_GTAProce]             MainThrd/ done removing resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[   1085016] [b2699_GTAProce]             MainThrd/ Stopping resource renzu_customs
[   1085016] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[   1085016] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[   1085016] [b2699_GTAProce]             MainThrd/ Started resource renzu_customs
[   1085016] [b2699_GTAProce]             MainThrd/ 
[   1085031] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[   1085141] [b2699_GTAProce]  UV loop: httpClient/ Required resources: renzu_customs 
[   1085156] [b2699_GTAProce]             MainThrd/ Creating script environments for renzu_customs
[   1085156] [b2699_GTAProce]             MainThrd/ Failed to load script @renzu_shield/init.lua.
[   1085156] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[   1085156] [b2699_GTAProce]             MainThrd/ loading CARCOLS_GEN9_FILE resources:/renzu_customs/data/carcols_gen9.meta.
[   1085156] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[   1085156] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[   1085156] [b2699_GTAProce]             MainThrd/ loading CARMODCOLS_GEN9_FILE resources:/renzu_customs/data/carmodcols_gen9.meta.
[   1085156] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols_gen9.meta in data file mounter class CExtraContentFileMounter.
[   1085156] [b2699_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[   1085172] [b2699_GTAProce]             MainThrd/ loading FIVEM_LOVES_YOU_447B37BE29496FA0 resources:/renzu_customs/data/carmodcols.ymt.
[   1085172] [b2699_GTAProce]             MainThrd/ done loading resources:/renzu_customs/data/carmodcols.ymt in data file mounter class CExtraContentFileMounter.
[   1085172] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Mounted renzu_customs (1 of 1)`

**Comment by Fakiee** [comment]
It was working, but I had a database Corruption, I imported the sql but it still doesn't stick

**Comment by renzuzu** [comment]
datas are saved in owned_vehicles
make sure you have money in inventory or society/qb-management

most common does not saving is the RGB colors, which needs a customisation in your garage.
but upgrades its should stick unless theres and error while saving the data in server, whats your showing is client side.
