### ISSUE TITLE
Repair Not Working

### ISSUE THREAD

**Issue by Fakiee** [renzuzu/renzu_customs#153]
When clicking repair it just sticks you there, It was working a few days ago, I have not changed anything in config or anything.

**Comment by Fakiee** [comment]
Anyone have any thoughts?

**Comment by renzuzu** [comment]
probably some error inclient? this repair requires progress bar resource.

**Comment by Fakiee** [comment]
I have renzu_progressbar, but when it was working it just instantly repaired, do I have to enable it in renzu_customs?

**Comment by Fakiee** [comment]
I found it lol, I use use Search to find stuff but I found it after that didn't work. 
(Im very new to all this haha)
