### ISSUE TITLE
Not enough money cabron

### ISSUE THREAD

**Issue by Julezzzz119** [renzuzu/renzu_customs#154]
I downloaded this script everything works except for when i got to pay for the upgrades not matter how much money i have or spend i apparently never have enough i'm using esx and i'm extremely confused.

**Comment by renzuzu** [comment]
framework?

look for qb-management or society if your using it. checks if you have specific job money

**Comment by Julezzzz119** [comment]
I have esx society

**Comment by Julezzzz119** [comment]
any updates?

**Comment by Julezzzz119** [comment]
also how would i access this garage
![Uploading Screenshot 2023-02-13 200512.png…]()
