### ISSUE TITLE
I cant add more tuning locations

### ISSUE THREAD

**Issue by SchwarzerMercedes** [renzuzu/renzu_customs#156]
I change shopcoord location but it dont show up on that place. Do somone please say what i doing wrong?

**Comment by renzuzu** [comment]
you have to change everything related to coordinates in the config

**Comment by SchwarzerMercedes** [comment]
Okay thanks i try it

**Comment by SchwarzerMercedes** [comment]
![image](https://user-images.githubusercontent.com/123660981/219874617-d75a9cab-e5c4-4ad0-90af-45dc3f8ec6c6.png)
I edit this coords but it dont show up i have to edit all coords like stockroom, paintmenu etc.?

**Comment by renzuzu** [comment]
change the radius to larger

**Comment by SchwarzerMercedes** [comment]
Okay it help my ty <3
