### ISSUE TITLE
Error Changue point mechanic

### ISSUE THREAD

**Issue by Densen013** [renzuzu/renzu_customs#158]
the job to have a double mechanic, the mechanic's points disappear, also when I try to change the mechanic's points it does the same thing. Mechanic points disappear completely! solution?

**Comment by Densen013** [comment]
Now it looks like this... I can't put 2 different mechanics, that is, 1 mechanic and a different one!

https://imgur.com/a/5gPYQhf

**Comment by renzuzu** [comment]
dont forget to change the radius
