### ISSUE TITLE
Way to set so everyone can access menu, but only do certain upgrades?

### ISSUE THREAD

**Issue by Tttony2x** [renzuzu/renzu_customs#16]
Currently, if Config.JobPermissionAll = false then everyone can access menu and do every upgrade
With Config.JobPermissionAll = true, only mechanic job can access menu and do every upgrade

What I'd like is with Config.JobPermissionAll = true, every job can access menu but can only do the upgrades their job grade appears under in the
```
		job_grade = { -- default job grade to access this Upgrade Feature (this option will work only if Config.JobPermissionAll is true
			['mecano'] = 0,
			['police'] = 0,-- police is sample only change this!
		},
```

and a way to make it open to all

So that mechanics are the only ones that can do performance upgrades, but everyone can do cosmetic upgrades

Sorry for asking for a lot, I like the script and will be using it anyway

**Comment by Tttony2x** [comment]
Script also does not seem to have support for pearlescent colors unless I'm missing something.

**Comment by renzuzu** [comment]
i will try what i can do in your request..

about Pearlescent https://github.com/renzuzu/renzu_customs/commit/87333f6254face41c92a9f120caff87bc642c59d

**Comment by renzuzu** [comment]
done
https://github.com/renzuzu/renzu_customs/commit/b6bced28c954b690a7e339d2a26a99ff5a290195
