### ISSUE TITLE
Invalid Vector Dimensions Error

### ISSUE THREAD

**Issue by Kingsman40** [renzuzu/renzu_customs#163]
I changed the coords for Bennys to another location. But I get this error:

`@renzu_customs/config.lua:76: bad argument #4 to vectors3 (invalid vector dimensions)`

Here is a screenshot of the config part. Line 76. All I did was change the coords.
https://i.postimg.cc/4x8Mb8fW/renzu-customs-error.png

**Comment by renzuzu** [comment]
weird my copy is vec3 format
