### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by WrecksBG** [renzuzu/renzu_customs#19]
When i try on upgrade menu camera move but not open UI menu (QBCore version)

**Comment by WrecksBG** [comment]
open*

**Comment by WrecksBG** [comment]
and i have this error when trying to put something into inventory

[script:renzu_customs] SCRIPT ERROR: @renzu_customs/server/server.lua:73: attempt to index a nil value (local 'result')
[script:renzu_customs] SCRIPT ERROR: @renzu_customs/server/server.lua:26: attempt to index a nil value (local 'result')

**Comment by renzuzu** [comment]
> When i try on upgrade menu camera move but not open UI menu (QBCore version)

are you using latest version? this is a about job grade, can you check your job configs.



> and i have this error when trying to put something into inventory
> 
> [script:renzu_customs] SCRIPT ERROR: @renzu_customs/server/server.lua:73: attempt to index a nil value (local 'result')
> [script:renzu_customs] SCRIPT ERROR: @renzu_customs/server/server.lua:26: attempt to index a nil value (local 'result')

this error should be fixed in latest commits (assuming you are using last week version)
this error appears on older FXServer version.

**Comment by renzuzu** [comment]
is the error still appearing in latest branch?
reopen if still a case
