### ISSUE TITLE
[SUGGESTIONG] Adding job restriction per shop 

### ISSUE THREAD

**Issue by ImpulseFPS** [renzuzu/renzu_customs#2]
Hello, this looks insane well done man.
Just a note I think would be cool adding job restriction per shop

**Comment by renzuzu** [comment]
i am actually thinking about this before i release the script..
but my logic is the same mechanic job, and the one stop me from doing it due to renzu_job script does not support dual job yet..

so a different job is a diffinitely possibele without breaking anything

ill see what i can do

**Comment by renzuzu** [comment]
applied
https://github.com/renzuzu/renzu_customs/commit/be14dfa289f8e2289d056cb30028baba946f9b96
please let me know if theres any issue, as i tested no problem so far

Changes:  
client/events.lua
client/function.lua
config.lua

**Comment by renzuzu** [comment]
jobs and min grade is handle by
Config.Customs

Menu Upgrade Job grade per mod Index is now possible

```
sample and default for all mod index for now

----------Hydraulics--------
	[38] = {
		job_grade = { -- default job grade to access this Upgrade Feature (this option will work only if Config.JobPermissionAll is true
			['mechanic'] = 0,
			['police'] = 0,-- police is sample only change this!
		},
		label = 'Hydraulics',
		name = 'hydraulics',
        index = 38,
		cost = 15000,
		percent_cost = 7,
		bone = 'wheel_rf',
        type = 'cosmetic',
	},
```
