### ISSUE TITLE
Props doesn't disappear

### ISSUE THREAD

**Issue by Manta95** [renzuzu/renzu_customs#20]
Hi Renzuzu,

I have a weird problem while my mechanic put customs on cars : 

![image](https://user-images.githubusercontent.com/64571534/134292376-9640112b-2e6c-4791-8deb-caffc51d6caf.png)

**Comment by renzuzu** [comment]
are you updated? i made the deletion of props server synced

**Comment by Manta95** [comment]
Woops, haven't see it, i update it right now, thanks ;)

**Comment by renzuzu** [comment]
if this is not fixed re open it, thank you!
