### ISSUE TITLE
using jobpermissionall but unable to pay without job money

### ISSUE THREAD

**Issue by Zhorteye** [renzuzu/renzu_customs#23]
I want my players to be able to pay with their cash/bank without a job having to have money, but still use JobPermissionAll to make it so only specific jobs have access to specific upgrades.. how would i do this?

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_customs/commit/379e476a82cce0ec640a5b04da403f7446928609

this will use own player money if renzu_jobs == false and PERMISSIONALL == true

you could change this to check jobmoney from QBCORE function
https://github.com/renzuzu/renzu_customs/blob/379e476a82cce0ec640a5b04da403f7446928609/server/server.lua#L101
and
this change it to qbcore removejob money ( i am not sure what is the code for that)
https://github.com/renzuzu/renzu_customs/blob/379e476a82cce0ec640a5b04da403f7446928609/server/server.lua#L142

you should edit it your self to use job money from qbcore (function) or qb society,

**Comment by renzuzu** [comment]
re open if you still need help 
Thank you
