### ISSUE TITLE
Cannot store items

### ISSUE THREAD

**Issue by nukestarz** [renzuzu/renzu_customs#24]
I cannot store items in the inventory. No  Press E to store

this function is not showing:  DrawMarkerInput(vector3(vec.coord.x,vec.coord.y,vec.coord.z),'Press [E] Store','renzu_customs:storemod',false,'store_mod',{currentprivate,mod,lvl,newprop},true)

![image](https://user-images.githubusercontent.com/65008430/134751267-def9ce58-6cab-4d94-a9d4-2692a2699758.png)

**Comment by nukestarz** [comment]
also Press [E] to Open Inventory is not working. It notifies but it will not pop up.

**Comment by nukestarz** [comment]
![image](https://user-images.githubusercontent.com/65008430/134751786-b2d5d2c3-8fcf-4d7c-b9fd-6b7d2cd5e74c.png)
When i press [E] nothing happens

**Comment by nukestarz** [comment]
![image](https://user-images.githubusercontent.com/65008430/134751856-3b65936b-0ba9-44ee-bc5f-e2662f82a9c8.png)
It prints this one on the db

**Comment by renzuzu** [comment]
hi brother , is this a default config, and latest update from mainbranch ?

did you try pressing E? in the marker
(the floating text) is hiding/showing every 5 seconds (for optimzation purpose) but it might be confusing like this.

so if you did Press E and the item is not store to inventory, it could be a bug that i need to repro.
as in my localhost i do can store it without the floatingtext (hide mode)

**Comment by nukestarz** [comment]
Yeah tried to press E on the marker and nothing happens. I am using the latest repo you released.

**Comment by nukestarz** [comment]
https://streamable.com/npskpl Check this video.

**Comment by renzuzu** [comment]
thank you brother i found it,
it was a typo of config

https://github.com/renzuzu/renzu_customs/commit/8166e10913fbe918c21a53354a85c0571c5f9a8a
