### ISSUE TITLE
Paintjob

### ISSUE THREAD

**Issue by gringoDiaz** [renzuzu/renzu_customs#26]
Paintjob not saving

**Comment by renzuzu** [comment]
make sure you use exports (advanced usage)

or your garage must support RGB paints

**Comment by renzuzu** [comment]
no your cant atm.
[qb-garages.zip](https://github.com/renzuzu/renzu_customs/files/7244883/qb-garages.zip)
this is the qb-garages modified with renzu_customs exports

**Comment by gringoDiaz** [comment]
Cool, thanks!
