### ISSUE TITLE
Important bug to update

### ISSUE THREAD

**Issue by nukestarz** [renzuzu/renzu_customs#27]
1. Bring your car to the upgrade blip then choose an upgrade
![image](https://user-images.githubusercontent.com/65008430/135165327-7120067a-c4e5-4f7c-87af-83848cae919d.png)

2. Apply upgrades anywhere you want
![image](https://user-images.githubusercontent.com/65008430/135165411-bcb399a0-61a3-4ea2-833f-74d4794a83f0.png)

3. Go F8 and quit
4. It saves the item you queued without paying for it
![image](https://user-images.githubusercontent.com/65008430/135165544-2036a39a-380b-472f-a96f-ae4904ab0f85.png)

**Comment by renzuzu** [comment]
this might be a little tricky i will try in couple of hour to update this

**Comment by renzuzu** [comment]
fixed https://github.com/renzuzu/renzu_customs/commit/a4e1714e268dd98b4defe856c12a8c3796e2b8b6

**Comment by nukestarz** [comment]
Thanks!
