### ISSUE TITLE
NUI Problem

### ISSUE THREAD

**Issue by nukestarz** [renzuzu/renzu_customs#28]
Hello, I experienced sometimes that the UI won't open when pressing [E]. It happens when opening Spray menu, Stocks menu and Inventory Menu

**Comment by nukestarz** [comment]
https://streamable.com/swcdst

**Comment by renzuzu** [comment]
I have to test it with popui

> sometimes that the UI won't open when pressing
So sometimes its not 100 percent occuring.
I might need a repro for this

**Comment by nukestarz** [comment]
ohh yeah you're correct. my bad HAHAH
