### ISSUE TITLE
Bug when previewing

### ISSUE THREAD

**Issue by nefariousxyz** [renzuzu/renzu_customs#35]
It saves the previewed upgrades and progressbar is not working

https://user-images.githubusercontent.com/65008430/136253776-553a77fc-e11a-4b55-95b8-1c68602c17f2.mp4

**Comment by nukestarz** [comment]
and paint is not saving to garage.

**Comment by nukestarz** [comment]
How?

**Comment by nukestarz** [comment]
hello any fixes on this?

**Comment by renzuzu** [comment]
somehow i cant reproduce the issue
i did exactly what you did, 
Tranny and Paint then Cancel
it return me the default/old paint.
