### ISSUE TITLE
Multiple Suggestions

### ISSUE THREAD

**Issue by Tttony2x** [renzuzu/renzu_customs#4]
Repairs menu as a config option
    A lot of servers probably use a different repair system, and would probably want this as an option
Customize local cars as a config option
   My server has cheap cosmetics, so people customize local cars often
Upgrade cost based on vehicle class?
   Currently on my server, PD cars are balanced around being upgraded, and upgrades are free. Being able to make upgrades free for any emergency class vehicle would be nice.

**Comment by renzuzu** [comment]
its done let me know if there is an issue ,Thank you

https://github.com/renzuzu/renzu_customs/commit/3207a9bf3cfead18f2e192e5238864c5c1511102
