### ISSUE TITLE
QBCORE NOT SAVING CUSTOM COLORS

### ISSUE THREAD

**Issue by Ciccioarmory** [renzuzu/renzu_customs#45]
Hello Renzu, as always we are really enjoying your scripts, i have a little problem with this one, when i set a custom color, save the car in a garage and the get it the color is the old one, basically it soesn-t save custom color

**Comment by renzuzu** [comment]
send me your garage, if its open source (link)
i can guide you

**Comment by Ciccioarmory** [comment]
Thank you!
https://github.com/qbcore-framework/qb-garages

**Comment by colonelnl** [comment]
I have the same problem.. and  use the same garage script

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_customs/issues/26#issuecomment-929280236

I uploaded a qbgarage in this issue page.

Its an old qb core 20 days ago
Already insert export of customs

So it should save everything
