### ISSUE TITLE
Removing and adding extras adds a lot of money

### ISSUE THREAD

**Issue by ZypsohDEV** [renzuzu/renzu_customs#46]
When we add and remove a extra the money doesnt change and if we add the extra the money ups and so if we do that a lot of times its gonna be expensive asf

**Comment by renzuzu** [comment]
Can you re explain sorry i dont get easily unless its really informTive also with image or clip will be help

**Comment by ZypsohDEV** [comment]
i will make a clip sorry for the late reply, my internet is not that good atm so i will take a while
