### ISSUE TITLE
Custom upgrades and resprays don't save

### ISSUE THREAD

**Issue by OffTheRipRP** [renzuzu/renzu_customs#49]
Some car upgrades don't save even resprays and I have renzu_garage. Any help will be great!

**Comment by polopokky** [comment]
Some car stickers are not safe.

**Comment by OffTheRipRP** [comment]
> Some car stickers are not safe.

Yea when i respray a car it doesn't save after the server restarts but i put it in the garage and everything so idk.

**Comment by renzuzu** [comment]
Enable renzu customs in garage config
Its disable by default

Rgb colors paints are saved by default and liveries too.

Unless theres an error after upgrading from menu, its possible else it should save everything

**Comment by OffTheRipRP** [comment]
> Enable renzu customs in garage config Its disable by default
> 
> Rgb colors paints are saved by default and liveries too.
> 
> Unless theres an error after upgrading from menu, its possible else it should save everything

Yea when i put custom turbos and things on cars they don't save even after I turned on renzu customs in the garage config.

**Comment by polopokky** [comment]
My section will save only the first stickers you change. Next time it won't save.
