### ISSUE TITLE
Adding all wheels from dlc's

### ISSUE THREAD

**Issue by Manta95** [renzuzu/renzu_customs#5]
Hi Renzuzu, it's Manta from cfx.re.

Here you have the line to have all wheels category including latest dlc's wheels (just have to create wheel image for html part) : 

list = {WheelType = {Sport = 0, Muscle = 1, Lowrider = 2, SUV = 3, Offroad = 4,Tuner = 5, BikeWheel = 6, HighEnd = 7, Dragster = 8, Street = 9, BennysWheel = 10, BespokeWheel = 11 } , WheelColor = allcolors, Accessories = { CustomTire = 1, BulletProof = 1, SmokeColor = 1, DriftTires = 1} }

**Comment by renzuzu** [comment]
i see this but i  havent tried it, i will try in next update.
 
 THank you for providing this

**Comment by Manta95** [comment]
I've tried and confirm it work ;)

Already do this for esx_lscustom ;)

**Comment by Manta95** [comment]
Corrected list : 

list = {WheelType = {Sport = 0, Muscle = 1, Lowrider = 2, SUV = 3, Offroad = 4,Tuner = 5, BikeWheel = 6, HighEnd = 7, BennysWheel = 8, BespokeWheel = 9, Dragster = 10, Street = 11 }

**Comment by renzuzu** [comment]
Added the Wheels their Beautiful
