### ISSUE TITLE
Stance options

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_customs#50]
So you've made the stancer menu why you won't implement it in the mechanic too? i think it's logic to a mechanic to do the stance work

**Comment by renzuzu** [comment]
Stancer is a item based.

Do you prefer stancer via the upgrade menu?,
Its hassle for players.

Stancer is like a suspension and camberkit

Owner should be able to adjust it anytime after installing.

**Comment by Dokman** [comment]
Yes but I mean, it's installed when the item is used, I mean a mechanic can be able to use the stance menu installed in that car

**Comment by ElusionPDX** [comment]
Just add a job check to it Dokman.
This is just a guide as your esx may be older or using exm.

> -------------------------------------------------------------------
> ESX = nil
> Citizen.CreateThread(function()
> 	while ESX == nil do
> 		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
> 		Citizen.Wait(10)
> 	end
> 
> 	while ESX.GetPlayerData().job == nil do
> 		Citizen.Wait(10)
> 	end
> 
> 	PlayerData = ESX.GetPlayerData()
> end)
> 
> RegisterCommand(Config.commands, function()
> if PlayerData.job ~= nil and PlayerData.job.name == 'YOUR JOB HERE' then
> 	OpenStancer()
> 	print("car control")
> 	end
> end, false)
> 
> CreateThread(function()
> 	RegisterKeyMapping(Config.commands, 'Open Car Control', 'keyboard', Config.keybinds)
> 	return
> end)
> -------------------------------------------------------------------
