### ISSUE TITLE
[Bug] No blips in Car meet interior

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_customs#51]
I am using
set sv_enforceGameBuild 2372
and the car meet map [Car Meet Interior](https://forum.cfx.re/t/free-mlo-car-meet-parking-lot-interior/4126159)

then i created a customs for the map and populated the coords

```
['Tuners Garage Auto Meet'] = { 
		job = 'tuners_mechanic', -- job name permmision for this shop
		min_grade = 0, -- min grade to access the whole shop feature
		radius = 30, -- radius for whole shop
		stockroom = {coord = vector4(121.79,-3028.63,7.04,80.82), grade = 0},
		paintmenu = {coord = vector3(128.07,-3009.74,7.04), grade = 0},
		garage_inventory = {coord = vector4(960.15,-2391.52,22.32,200.44), grade = 0},
		shopcoord = vector4(859.68,-2364.96,30.35,355.95),
		mod = {
			{coord = vector4(912.43,-2361.43,20,253.05), taken = false},
		},
		Blips = {sprite = 446, color = 68, scale = 0.8}
    },
```

but after this i cant have my customs in the map
![image](https://user-images.githubusercontent.com/2290904/139613602-f9f9c6e1-8376-4da4-89bb-a059c5d8eaa7.png)

**Comment by renzuzu** [comment]
Did you solved this?
This is like moving the coord right?

It should not be an issue unless there is other problem

**Comment by Dokman** [comment]
So what should be the problem? I cannot fix it, and the markers not appear

**Comment by Manta95** [comment]
Z must be Z, not z -1

**Comment by ElusionPDX** [comment]
you have   912.43, -2361.43, 20, 253.05
Your z is missing the rest of the coord. some scripts will work with out it and some dont. 
Tested your config with a proper Z and its working fine.
		mod = {
			{coord = vector4(912.43, -2361.43, 20, 253.05), taken = false},
		},
Also your shop and others are way out of range for the mod shop.
Here is what i changed to make it all show

`['Tuners Garage Auto Meet'] = { 
		job = 'mechanic', -- job name permmision for this shop
		min_grade = 0, -- min grade to access the whole shop feature
		radius = 30, -- radius for whole shop
		stockroom = {coord = vector4(907.0578, -2354.2935, 18.2080, 89.1386), grade = 0},
		paintmenu = {coord = vector3(907.0578, -2354.2935, 18.2080), grade = 0},
		garage_inventory = {coord = vector4(907.0578, -2354.2935, 18.2080, 89.1386), grade = 0},
		shopcoord = vector4(907.0578, -2354.2935, 21.2080, 89.1386),
		mod = {
			{coord = vector4(910.4331, -2361.5576, 20.6446, 44.2972), taken = false},
		},
		Blips = {sprite = 446, color = 68, scale = 0.8}
    },`

**Comment by Dokman** [comment]
Oh thanks I didn't know that I can change it, thanks

**Comment by Dokman** [comment]
![image](https://user-images.githubusercontent.com/2290904/140628738-fbb1167d-a560-4148-af36-e701a53cd604.png)

**Comment by ElusionPDX** [comment]
I dont know what your trying to show?
The config i posted above is set to the job mechanic and is just to the side of were your parked as it shows on your map.
![image](https://user-images.githubusercontent.com/19332765/140683761-e5e018ed-3e28-489f-9a88-660be1c2ee03.png)

**Comment by Dokman** [comment]
But it wasn't showing any blip
