### ISSUE TITLE
Vehicle Extras glitch

### ISSUE THREAD

**Issue by ZypsohDEV** [renzuzu/renzu_customs#55]
Hi renzu i deleted my other issue by mistake but here is the video i remove the extra and it adds price

https://user-images.githubusercontent.com/92858087/141186706-9b47ad36-d123-47d9-888f-c9a411252158.mp4

**Comment by iiCarelessness** [comment]
same problem with other parts.

**Comment by ZypsohDEV** [comment]
for me its just with extras

**Comment by Webby0815** [comment]
Yes , @mthe same :-/
