### ISSUE TITLE
The tuner don't Work

### ISSUE THREAD

**Issue by Fabicraft3D** [renzuzu/renzu_customs#58]
If I sit in the Car I can only Tune Front Bumper nothing else...
![Bild_2021-11-21_180336](https://user-images.githubusercontent.com/61612289/142771769-7feedb5c-66cb-4193-ab4c-afb59bc7e661.png)

**Comment by Manta95** [comment]
Jester or modded car?

**Comment by Fabicraft3D** [comment]
> Jester or modded car?

For each car...

**Comment by Manta95** [comment]
Maybe you have a conflict with modded cars who use the same modkit id in carcols.meta and carvariations.meta ?
