### ISSUE TITLE
Spraying dont work

### ISSUE THREAD

**Issue by Orlexor** [renzuzu/renzu_customs#59]
Greetings!

i tried to fix it myself but im a rookie so i got fast to my limits.

I can choose a Colour in the Spray Paint Menu, but after that nothing happends.
Everything else is working (so far i know) as intended. 

https://i.gyazo.com/57375d6b805b3f758ecdf307460b17bb.mp4

I didnt do much with the script then follow your Installation.

**Comment by Orlexor** [comment]
I changed today Config.usePopui = true and Config.showmarker = false
And tested it again.

https://gyazo.com/38748c25a8efc1d4d8c20e5f83baac09

**Comment by Manta95** [comment]
You have to go near the car then press E and it opens the menu to spray

**Comment by Orlexor** [comment]
> You have to go near the car then press E and it opens the menu to spray

Yeah i know... but in the preview my Char should get the spray prop and the spray menu. But it isnt showing up.
