### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by NegraLyda** [renzuzu/renzu_customs#63]
![Ekran Alıntısı](https://user-images.githubusercontent.com/86746241/143718804-1ea78124-51a0-4390-88a2-4450caa25dcb.PNG)

This is the error. I can't use anything about script. Can see blips but when i trying to interaction it happens.

**Comment by renzuzu** [comment]
What framework?

If thisnis qbcore change the shared export in cl and sv wrapper in framework folder

**Comment by NegraLyda** [comment]
> What framework?
> 
> If this is qbcore change the shared export in cl and sv wrapper in framework folder

uhm.. i didn't understand what do you mean can u explain more?
