### ISSUE TITLE
car parts stuck in players hands

### ISSUE THREAD

**Issue by biskfather** [renzuzu/renzu_customs#7]
![2021 09 13-10 29](https://user-images.githubusercontent.com/80595080/133063288-3c06f25c-1652-42f8-8e2e-a1a062852b3c.png)

**Comment by biskfather** [comment]
pressed E on car to view parts, clicked hood and the part wont go away

**Comment by renzuzu** [comment]
wait ,  did you try storing it? to the inventory?

when you pull out parts , its meant to store in Inventory.

**Comment by biskfather** [comment]
Oh then it didnt store to the inventory, it stayed in my hands

**Comment by biskfather** [comment]
I'm using esx_inventoryhud if that helps

**Comment by renzuzu** [comment]
no i mean the inventory in script.
check the config coordinates and find the inventory to store the item.

**Comment by biskfather** [comment]
Ok I'll try and report back

**Comment by driftonez** [comment]
i sort of have this issue, once ive got parts in my hands i cant store them
