### ISSUE TITLE
Extras menu seems to be not functioning properly.

### ISSUE THREAD

**Issue by ambroseautomation** [renzuzu/renzu_customs#72]
Hello I've been trying to figure out why the only option that gives me extras is the first option and it gives me all the extras. None of the other extras buttons work. I'm using ESX Legacy and I have not yet modified the script.

**Comment by TheOnlyNecro** [comment]
did you ever figure this out Im having the same issue.

**Comment by TheOnlyNecro** [comment]
Yeah I love his scripts but I looms like he won't support them
