### ISSUE TITLE
QBCORE - No Such Export

### ISSUE THREAD

**Issue by Phantomawe** [renzuzu/renzu_customs#75]
Hi Renzuzu,

Love the look of your work trying to get a couple of the mods added in I have all the dependancies the most up to date QBcore version and your most recent download of Renzu_customs but getting the below error where GetSharedObject does not seem to exist in qb-core any clue?

https://i.imgur.com/s1Bofny.png

Kind Regards
Phantom

**Comment by Natedawg63** [comment]
> Hi Renzuzu,
> 
> Love the look of your work trying to get a couple of the mods added in I have all the dependancies the most up to date QBcore version and your most recent download of Renzu_customs but getting the below error where GetSharedObject does not seem to exist in qb-core any clue?
> 
> https://i.imgur.com/s1Bofny.png
> 
> Kind Regards Phantom

Gotta edit the top lines of framework - cl_wrapper.lua and svwrapper.lua. The import function of QBCore has changed and just needs updating. Should say GetCoreObject now.

elseif Config.framework == 'QBCORE' then
		QBCore = exports['qb-core']:GetCoreObject()
		while QBCore == nil do Wait(0) end
		QBCore.Functions.GetPlayerData(function(p)
			PlayerData = p
			if PlayerData.job ~= nil then
				PlayerData.job.grade = PlayerData.job.grade.level
			end
        end)
	end

**Comment by Phantomawe** [comment]
@Natedawg63 Thank you this fixed the issue :)
