### ISSUE TITLE
New coordinate bug?

### ISSUE THREAD

**Issue by xsoskiller** [renzuzu/renzu_customs#76]
I'm trying to add new coordinate for Customs and nothing appears. does anyone could help me?

here a sample of what i'm adding as coordinate
`['LS_Custom'] = { -- Shop id -- Custom Map Tuner Garage (2372 Build only, canary and release) IPL and Int https://forum.cfx.re/t/free-mlo-tuner-auto-shop/4247145
		job = 'mechanic', -- job name permmision for this shop
		min_grade = 0, -- min grade to access the whole shop feature
		radius = 100, -- radius for whole shop
		stockroom = {coord = vector4(-350.56024169922,-172.148681164063,39.01512527566,200.2949066162), grade = 0},
		paintmenu = {coord = vector3(-317.05117797852,-93.23741668701,39.03767776489), grade = 0},
		paintmenu = {coord = vector3(-324.48928833008,-90.83637237549,39.03767776489), grade = 0},        
		garage_inventory = {coord = vector4(-328.41223144531,-157.97546386719,39.01512527566,266.3261108398), grade = 0},
		shopcoord = vector4(818.54309082031,-953.44543457031,26.108730316162,305.57107543945),
		mod = {
            {coord = vector4(-364.50643920898,-86.19000244141,38.60093688965,67.5348739624), taken = false},
            {coord = vector4(-364.50643920898,-86.19000244141,38.60093688965,67.5348739624), taken = false},
            {coord = vector4(-364.50643920898,-86.19000244141,38.60093688965,67.5348739624), taken = false},
		},
		Blips = {sprite = 446, color = 68, scale = 0.8},
    },
}`

**Comment by DrJoker29** [comment]
We have the same Problem do you have a solution?

**Comment by Xence69** [comment]
> I found one solution you hace to put more radios of the shop and that it For example 30 to 300000000000 I do that

can u show an example pls, i don't understand what you mean :/

**Comment by xsoskiller** [comment]
There is my solution (sry for the long wait)
Config.Customs = { -- Multiple Shop Start

    ['Bennys'] = { -- Shop id -- Sample bennys (IPL coordinates) Change this to your liking (CHANGE COORDINATES IF CUSTOM BENNYS MAP)
		job = 'mechanic', -- job name permmision for this shop
		min_grade = 0, -- min grade to access the whole shop feature
		radius = 30, -- radius for whole shop
		stockroom = {coord = vector4(-227.70811462402,-1322.9874267578,30.890409469604,90.902221679688), grade = 0}, -- vector 4 why the F is this vector4, x,y,z,w (heading)
		paintmenu = {coord = vector3(-228.27142333984,-1333.4058837891,30.89038848877), grade = 0},
		garage_inventory = {coord = vector4(-200.8703918457,-1317.6979980469,31.089340209961,267.89974975586), grade = 0},
		shopcoord = vector4(-212.58630371094,-1325.0119628906,30.89038848877,157.28034973145),
		mod = {
			{coord = vector4(-224.20236206055,-1329.8156738281,30.21583366394,87.278968811035), taken = false},
			{coord = vector4(-213.22569274902,-1331.546875,30.215799331665,356.6969909668), taken = false},
		},
		Blips = {sprite = 446, color = 68, scale = 0.8},
    },
    
['LS_Custom'] = { -- Shop id -- Custom Map Tuner Garage (2372 Build only, canary and release) IPL and Int https://forum.cfx.re/t/free-mlo-tuner-auto-shop/4247145
		job = 'mechanic', -- job name permmision for this shop
		min_grade = 0, -- min grade to access the whole shop feature
		radius = 100, -- radius for whole shop
		stockroom = {coord = vector4(-350.56024169922,-172.148681164063,39.01512527566,200.2949066162), grade = 0},
		paintmenu = {coord = vector3(-317.05117797852,-93.23741668701,39.03767776489), grade = 0},
		paintmenu = {coord = vector3(-324.48928833008,-90.83637237549,39.03767776489), grade = 0},        
		garage_inventory = {coord = vector4(-328.41223144531,-157.97546386719,39.01512527566,266.3261108398), grade = 0},
		shopcoord = vector4(-330.52465820313,-116.25479888916,39.0138130168,305.57107543945),
		mod = {
            {coord = vector4(-364.50643920898,-86.19000244141,38.60093688965,67.5348739624), taken = false}, --Truck dock 1
            {coord = vector4(-352.85,-90.08,39.01,67.5348739624), taken = false}, --Truck dock 2
            {coord = vector4(-339.04,-95.14,39.01,67.5348739624), taken = false}, --Truck dock 3
            {coord = vector4(-342.67000000000,-113.88000000000,39.02000000000,258.25000000000), taken = false},--Car Dock 1
            {coord = vector4(-346.91,-124.55,39.02,258.25), taken = false},--Car Dock 2
                        {coord = vector4(-349.69,-131.34,39.02,258.25), taken = false},--Car Dock 3
                        {coord = vector4(-326.69,-144.43,39.01,72.11), taken = false},--Car Dock 4
                        {coord = vector4(-324.86,-139.02,39.01,72.11), taken = false},--Car Dock 5
                        {coord = vector4(-322.95,-133.98,39.01,72.11), taken = false},--Car Dock 6
                        {coord = vector4(-321.00,-128.72,39.01,72.11), taken = false},--Car Dock 7
                        {coord = vector4(-319.02,-123.63,39.01,72.11), taken = false},--Car Dock 8
                        {coord = vector4(-317.50,-118.23,39.01,72.11), taken = false},--Car Dock 9
                        {coord = vector4(-315.43,-113.22,39.01,72.11), taken = false},--Car Dock 10
                        {coord = vector4(-313.62,-108.09,39.01,72.11), taken = false},--Car Dock 11
                        {coord = vector4(-311.62,-102.86,39.01,72.11), taken = false},--Car Dock 12
		{coord = vector4(-317.05117797852,-93.23741668701,39.037677764895,67.5348739624), taken = false}, --Paint shop 1
        {coord = vector4(-324.48928833008,-90.83637237549,39.03767776489,67.5348739624), taken = false},--paint shop 2
        },
		Blips = {sprite = 446, color = 68, scale = 0.8},
    },
}
i have 2 Custom Shop configured and both work well
