### ISSUE TITLE
Discount per job?

### ISSUE THREAD

**Issue by Tttony2x** [renzuzu/renzu_customs#8]
Would it be possible to make certain (or all) upgrades cheaper for a certain job?
ex: mechanic customization options are 20% cheaper, but others can still do them

**Comment by renzuzu** [comment]
Its possible.
Maybe its better to set discount for all upgrade type?
Or is there a special reason to set discount per mods?

**Comment by Dokman** [comment]
i think it's a better way to have both, so a boss can reward an type of part in the car, or make cheaper for a better type of employee

**Comment by Tttony2x** [comment]
Both is fine - 
Reason for the request is that on my server, only mechanics will be able to do performance upgrades. Everyone will be able to do customization, but it will be cheaper for mechanics.

Thus, since only mechanics will be doing performance upgrades, it doesnt need to be cheaper really cause they'll be the only one. But more options are better generally.

Also - possible to set some upgrades require job and some don't without listing every job?
ex:
ornaments does not require job, but hood does

Thank you!

**Comment by renzuzu** [comment]
its done
https://github.com/renzuzu/renzu_customs/commit/3d17a7e721173de436755c2f13b9cc9ed4cce951

**Comment by Tttony2x** [comment]
Appreciate you, such good work. From what I'm looking at I don't think it's pulling upgrade price from DB, but it might be looking at the wrong table? Do you know what lines I could look at for this?
`Config.VehicleValuetoFormula = true`
is enabled

**Comment by renzuzu** [comment]
oh i forgot theres a global variable for cost
sorry
https://github.com/renzuzu/renzu_customs/commit/e67caffb9d1872b09389a176b13968d5025430b9
