### ISSUE TITLE
Pay Bug ?

### ISSUE THREAD

**Issue by Webby0815** [renzuzu/renzu_customs#84]
when you look at the tuner
1. On turbo
2. click on racing
3. click on default (the more often you click on default, the more money you go into the minus, so if you press 10 times you can tune free)

**Comment by Webby0815** [comment]
??????????????????

**Comment by LostJ3ster** [comment]
Not 100% sure, since I fixed it for me a while ago, but:
Some parts just lower/raise the number, with no attention to whats already been on the list.
Because of that, changing the color via color wheel will raise the price to infinity.

That has to be fixed in script.js.
If you need help with that, just let me know. Shouldn't be that hard.

**Comment by Webby0815** [comment]
ja ,bitte hilf mir ....

**Comment by BTNGaming** [comment]
> Not 100% sure, since I fixed it for me a while ago, but: Some parts just lower/raise the number, with no attention to whats already been on the list. Because of that, changing the color via color wheel will raise the price to infinity.
> 
> That has to be fixed in script.js. If you need help with that, just let me know. Shouldn't be that hard.

Hey if you are still good with helping out, wouldn't mind grabbing a copy of the fixed/updated version from you if available. BTNGaming#7728 (Discord)

**Comment by LostJ3ster** [comment]
> ja ,bitte hilf mir ....

Send me your Discord, we can fix it via Screen Share if you‘d like to



> > Not 100% sure, since I fixed it for me a while ago, but: Some parts just lower/raise the number, with no attention to whats already been on the list. Because of that, changing the color via color wheel will raise the price to infinity.
> > That has to be fixed in script.js. If you need help with that, just let me know. Shouldn't be that hard.
> 
> Hey if you are still good with helping out, wouldn't mind grabbing a copy of the fixed/updated version from you if available. BTNGaming#7728 (Discord)

Same as Webby0815, I cant give you a copy, since I‘ve changed too much, but we can solve the issues on Discord if you want to

**Comment by nizmogr** [comment]
Why don't you share the fix here so everybody can fix it too?
