### ISSUE TITLE
Blimp shows up but cannot interact with shop menu

### ISSUE THREAD

**Issue by C4tv** [renzuzu/renzu_customs#95]
So I installed it the blimps I did the location you can see the blimp on the map you go there you make sure you have the job and you cannot do anything you can't upgrade the car you cannot paint it nothing trying to figure out what's wrong with it can anybody help me it has no errors

**Comment by LostJ3ster** [comment]
Take a look at the "mod" points themselves, and the "shopcoord" defined in Config.Customs.
Either try to move the mod points towards the shopcoord, or try to make the radius bigger.
Pressing E on a mod point outside the radius will cause the menu to not show at all, but not show any errors too.
