### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by JezuzRP** [renzuzu/renzu_customs#98]
is there anyway possible to get it to have a free camera to look at the vehicles better?? when trying to change the wheels i can barely see the wheels im changing!

**Comment by LostJ3ster** [comment]
On the bottom of the script.js there is an keyhandler. I've changed it to use "G" (71) as the toggle key. The ToggleCamera event already exists:
`$(document).on('keydown', function (event) {
    switch (event.keyCode) {
        case 27: // ESC
            document.getElementById("custom").innerHTML = '';
            $.post('https://renzu_customs/Close');
            break;
        case 9: // TAB
            break;
        case 17: // TAB
            break;
        case 71: // G
            $.post('https://renzu_customs/ToggleCamera');
            break;
}
});`

In client/nui_event.lua around line 170 there is the handler, beginning with "RegisterNUICallback('ToggleCamera', function(data, cb)"...
There you can find a IsControlPressed(0, 38)
38 on default describes the "E" key. Edit it on your liking.
Restart your script, and enjoy the ability to toggle camera mode.

**Comment by kaptenecha** [comment]
thanks a lot, fix my problem
